#!/bin/bash
set -e
# Compiler and linker flags
CXX="clang"
CXXFLAGS="-std=c17 -Wall -Wextra -g" # -g for debugging
LDFLAGS="-L. -lraylib -framework Cocoa -framework OpenGL -framework IOKit -framework CoreAudio -framework CoreGraphics -Wunused-parameter"

# Source file and output executable
SRC_FILE="./lib.c ./ultimateraylib/libEGL.dylib ultimateraylib/libGLESv2.dylib"
OUTPUT_EXEC="ultimateraylib/libAppleSillicon.dylib"
echo "Compiling $SRC_FILE..."
$CXX $CXXFLAGS -shared $SRC_FILE -o $OUTPUT_EXEC $LDFLAGS -Wl,-all_load
$CXX $CXXFLAGS -shared $SRC_FILE -o what.s $LDFLAGS -S -Wl,-all_load
if [ $? -eq 0 ]; then
    echo "Compilation successful."
    nm -gU ultimateraylib/libAppleSillicon.dylib > ultimateraylib/symboltable.txt
    install_name_tool -change ./libEGL.dylib   @loader_path/libEGL.dylib ultimateraylib/libAppleSillicon.dylib
    install_name_tool -change ./libGLESv2.dylib @loader_path/libGLESv2.dylib ultimateraylib/libAppleSillicon.dylib
else
    echo "Compilation failed."
fi
echo WINDOWS
#/opt/homebrew/Cellar/mingw-w64/13.0.0_2/toolchain-x86_64/bin/x86_64-w64-mingw32-gcc /Users/annes/Documents/some_games/ultimateraylib/lib.c -shared /Users/annes/Downloads/raylib-5.5_win64_mingw-w64/lib/raylib.dll 
#    -o ultimateraylib/libwin86_64.dll -I. -Wall -Wextra -g -Wunused-parameter
#zig cc -target x86_64-windows-gnu lib.c \
#    -D_WIN32 -DBUILD_LIBTYPE_SHARED -nostartfiles \
#    -g \
#    -Wl,--export-all-symbols \
#    -Lultimateraylib -lraylib \
#    -shared -o ultimateraylib/libwin86_64.dll

#echo LINUX
#zig cc -target x86_64-linux-gnu lib.c libraylib.so.5.5.0 -shared -o ultimateraylib/liblinux86_64.so

#x86_64-w64-mingw32-objdump -x ultimateraylib/libwin86_64.dll | grep "Export Table"
#x86_64-w64-mingw32-objdump -p ultimateraylib/libwin86_64.dll #| grep "InitWindow"
